# App Info
application: wgi-buzz
version: 7
runtime: python27
api_version: 1
threadsafe: yes

# Cache expiration
default_expiration: "30d"

# Files to ignore
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?

builtins:
- appstats: on
- remote_api: on

# Handlers
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: static/favicon\.ico

- url: /(robots\.txt|humans\.txt)
  static_files: \1
  upload: static/(robots\.txt|humans\.txt)

- url: /assets
  static_dir: static/assets

- url: /css
  static_dir: static/css

- url: /data
  static_dir: static/data

- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /.*
  script: WGIbuzz.app

# Libraries
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
